# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Cine\gui\ventana_buscar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_busqueda(object):
    def setupUi(self, ventana_busqueda):
        ventana_busqueda.setObjectName("ventana_busqueda")
        ventana_busqueda.resize(569, 430)
        self.tblResultados = QtWidgets.QTableWidget(ventana_busqueda)
        self.tblResultados.setGeometry(QtCore.QRect(0, 60, 561, 361))
        self.tblResultados.setObjectName("tblResultados")
        self.tblResultados.setColumnCount(0)
        self.tblResultados.setRowCount(0)
        self.widget = QtWidgets.QWidget(ventana_busqueda)
        self.widget.setGeometry(QtCore.QRect(10, 20, 551, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(13)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtBuscar = QtWidgets.QLineEdit(self.widget)
        self.txtBuscar.setBaseSize(QtCore.QSize(0, 9))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.txtBuscar.setFont(font)
        self.txtBuscar.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.txtBuscar.setObjectName("txtBuscar")
        self.horizontalLayout.addWidget(self.txtBuscar)
        self.btnAceptar = QtWidgets.QPushButton(self.widget)
        self.btnAceptar.setMaximumSize(QtCore.QSize(70, 16777215))
        self.btnAceptar.setObjectName("btnAceptar")
        self.horizontalLayout.addWidget(self.btnAceptar)
        self.btnCancelar = QtWidgets.QPushButton(self.widget)
        self.btnCancelar.setMaximumSize(QtCore.QSize(70, 16777215))
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout.addWidget(self.btnCancelar)

        self.retranslateUi(ventana_busqueda)
        QtCore.QMetaObject.connectSlotsByName(ventana_busqueda)

    def retranslateUi(self, ventana_busqueda):
        _translate = QtCore.QCoreApplication.translate
        ventana_busqueda.setWindowTitle(_translate("ventana_busqueda", "Busqueda de películas"))
        self.btnAceptar.setText(_translate("ventana_busqueda", "Aceptar"))
        self.btnCancelar.setText(_translate("ventana_busqueda", "Cancelar"))
